update codeowners
launchdarkly/ld-find-code-refs pull request #261
Opened 2022-08-25 16:12 UTC by jazanne

Add docs reviewers

2022-08-25 16:13 UTC, ember-stevens requested changes

2022-08-25 16:13 UTC, ember-stevens commented on CODEOWNERS
> +# Documenation
```suggestion
# Documentation
```

2022-08-25 18:24 UTC, ember-stevens approved these changes

2022-08-30 19:50 UTC, tiffanylphan approved these changes

2022-08-30 19:50 UTC, merged