update codeowners
launchdarkly/ld-find-code-refs pull request #442
Opened 2024-03-26 18:49 UTC by jazanne

2024-03-26 19:15 UTC, zmdavis approved these changes

2024-03-26 20:36 UTC, lucywyman requested changes
Hm I'm seeing some errors:
 ```


    Unknown owner on line 3: make sure the team @launchdarkly/team-app-platform-product exists, is publicly visible, and has write access to the repository

    * @launchdarkly/team-app-platform-product

    Unknown owner on line 9: make sure the team @launchdarkly/team-app-platform-product exists, is publicly visible, and has write access to the repository

    vendor/ @launchdarkly/team-app-platform-product

    Unknown owner on line 12: make sure the team @launchdarkly/team-app-platform-product exists, is publicly visible, and has write access to the repository

    CHANGELOG.md @launchdarkly/team-app-platform-product
```

2024-03-26 21:01 UTC, jazanne commented
@lucywyman i have this PR out there...hopefully it fixes the errors seen here https://github.com/launchdarkly/terraform/pull/13151

2024-03-27 14:04 UTC, jazanne commented
@lucywyman those errors are fixed now

2024-03-27 16:24 UTC, lucywyman approved these changes

2024-03-27 16:24 UTC, merged